version: "3.8"

services:
  landing:
    build: .
    container_name: landing
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.landing.rule=Host(`batutinhas.nova-classe.com`)"
      - "traefik.http.routers.landing.entrypoints=websecure"
      - "traefik.http.routers.landing.tls.certresolver=cloudflare"
      - "traefik.http.services.landing.loadbalancer.server.port=80"

networks:
  proxy:
    external: true